# Generated by Django 4.0.4 on 2022-08-21 17:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=25)),
                ('DOB', models.DateField()),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Email', models.EmailField(max_length=30)),
                ('Street', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=20)),
                ('PINCODE', models.CharField(max_length=7)),
            ],
        ),
    ]
