# Generated by Django 4.0.4 on 2022-08-21 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='\\d{9,13}')]),
        ),
    ]
