# Generated by Django 4.0.4 on 2022-08-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('otp', models.IntegerField()),
            ],
        ),
    ]
