# Generated by Django 4.0.4 on 2022-08-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_otp_handler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp_handler',
            old_name='otp',
            new_name='last_otp',
        ),
    ]
